### ISSUE TITLE
How to compute inception score with the  images produced by Wgan?

### ISSUE THREAD

**Issue by tlss94** [wiseodd/generative-models#41]
Hi,

Do you know how to reshape image output by your code in order to get inception score (I guess this code is for coloured images).

here is the inception github code:
https://github.com/openai/improved-gan/tree/master/inception_score

Thanks in advance

**Comment by LukasMosser** [comment]
You could pretrain a single channel classifier and compute it on the grayscale mnist images.

**Comment by tlss94** [comment]
But I mean a more straighforward way to compute it by reshaping the image outputed by this wgan code.

**Comment by LukasMosser** [comment]
Add 2 channels of zeros? Should give you an image in full blue, red or green. No activations from other channels. But not sure how meaingful that score would be.

**Comment by tlss94** [comment]
yes im not sure if that would be meaningful too 
also I didn t see a lot of inception score for greyscale pictures....

**Comment by wiseodd** [comment]
Hi,
It's not widely used because it relies on (pretrained) Inception model, which has 3-channel input.
As @LukasMosser said, you might try, but I'm not sure if the score is really meaningful for MNIST.

**Comment by sriharshasv** [comment]
I was faced with a similar problem of quantifying the quality of mnist-like images generated by GAN. I don't think inception score is the best metric for this. Instead of that, I trained an mnist classifier (CNN) with 10 dimensional output. For example, if the input image is of digit 2, then the output expected is [0,0,1,0,0,0,0,0,0,0]. You can find such models available on Github.Now, if you give this classifier an image where each pixel is random noise, it cannot be sure of that picture belonging to any class. Hence, it will output something like [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1].

This could be your quality metric, i.e., for an image, if the classifier's output is close to 0 or 1 for all classes, then the image is good. If the output is near 0.1, then the image is bad. So you just need to come up with a function that gives higher values when output is close to 0 or 1 for each class. something like  - (x0)*(1-x0)*(x1)*(1-x1)*....*(x9)*(1-x9)
where xi is the ith element of the output.

While the above function will mostly not work very well, you can play around with constants, check what the classifier outputs for different images and come up with one easily.

**Comment by gokul-uf** [comment]
a hacky way to do it is to just convert Grayscale to RGB where black in the grayscale is still black in RGB. see: https://stackoverflow.com/questions/21596281/how-does-one-convert-a-grayscale-image-to-rgb-in-opencv-python-for-visualizing
